export const mockCurrentState = {
  stateId: "STATE-BR",
  stateName: "Bihar",
  nodalDepartment: "Planning & Development Department, Govt of Bihar",
  headquarters: "Vikas Bhawan, Bailey Road, Patna",
  totalDistricts: 38,
  nodalSecretary: "Shri S. Siddharth, IAS (Principal Secretary)",
};

export const mockBiharDistrictsData = [
  { district: "Patna", totalWorks: 285, sanctionedCr: 142.5, completed: 198, flaggedCount: 48, avgRiskScore: 68, highRisk: 22, medRisk: 18, lowRisk: 8 },
  { district: "Gaya", totalWorks: 210, sanctionedCr: 104.0, completed: 145, flaggedCount: 36, avgRiskScore: 62, highRisk: 16, medRisk: 14, lowRisk: 6 },
  { district: "Muzaffarpur", totalWorks: 195, sanctionedCr: 98.2, completed: 130, flaggedCount: 32, avgRiskScore: 59, highRisk: 14, medRisk: 12, lowRisk: 6 },
  { district: "Bhagalpur", totalWorks: 180, sanctionedCr: 88.0, completed: 122, flaggedCount: 28, avgRiskScore: 55, highRisk: 12, medRisk: 10, lowRisk: 6 },
  { district: "Saran", totalWorks: 175, sanctionedCr: 84.5, completed: 110, flaggedCount: 31, avgRiskScore: 64, highRisk: 15, medRisk: 11, lowRisk: 5 },
  { district: "Darbhanga", totalWorks: 168, sanctionedCr: 82.0, completed: 118, flaggedCount: 25, avgRiskScore: 52, highRisk: 10, medRisk: 10, lowRisk: 5 },
  { district: "Purnia", totalWorks: 154, sanctionedCr: 74.0, completed: 102, flaggedCount: 24, avgRiskScore: 54, highRisk: 11, medRisk: 8, lowRisk: 5 },
  { district: "Nalanda", totalWorks: 162, sanctionedCr: 78.5, completed: 124, flaggedCount: 19, avgRiskScore: 46, highRisk: 7, medRisk: 8, lowRisk: 4 },
  { district: "Begusarai", totalWorks: 148, sanctionedCr: 71.0, completed: 105, flaggedCount: 21, avgRiskScore: 50, highRisk: 9, medRisk: 8, lowRisk: 4 },
  { district: "Samastipur", totalWorks: 158, sanctionedCr: 76.2, completed: 108, flaggedCount: 21, avgRiskScore: 48, highRisk: 8, medRisk: 9, lowRisk: 4 },
];

export const mockCurrentDistrict = {
  districtId: "DIST-BR-PATNA",
  districtName: "Patna",
  state: "Bihar",
  nodalOfficer: "Dr. Chandrashekhar Singh, IAS (DM & District Nodal Officer)",
  headquarters: "Patna Collectorate, Bihar",
  totalActiveWorks: 18,
  totalSanctionedCr: 14.8,
};

export const mockCurrentMp = {
  mpId: "MP-BR-0412",
  mpName: "Shri Ravi Shankar Prasad",
  constituency: "Patna Sahib",
  state: "Bihar",
  district: "Patna",
  term: "17th / 18th Lok Sabha",
  house: "Lok Sabha",
  annualEntitlementCr: 5.0, // ₹5.00 Crore annual MPLADS entitlement (500 Lakhs)
};

export const mockWorksData = [
  {
    workId: "MPLADS-BR-2024-0412",
    mpName: "Shri Ravi Shankar Prasad",
    state: "Bihar",
    district: "Patna",
    category: "Rural Roads & Bridges",
    description: "Construction of Bituminous Link Road from Didarganj to Sabalpur Panchayat",
    recommendedDate: "2023-04-12",
    sanctionDate: "2023-06-20",
    completionDate: "2024-02-15 (Overdue)",
    sanctionedAmount: 85.50, // Lakhs
    expenditure: 121.40,     // Overrun
    status: "Delayed",
    riskScore: 92,
    riskLevel: "High",
    flagReason: "Cost overrun by 42% and 9-month milestone stall",
    vendorName: "M/s Apex Infra Projects",
    riskFactorBreakdown: {
      costOverrun: 45,
      delaySlippage: 32,
      duplicateSimilarity: 13,
      vendorAnomaly: 10,
    },
    aiDiagnosticSummary: "Automated audit detected an unapproved ₹35.9L billing surge during Q3 alongside zero physical progress geotag updates since November 2023.",
    constituency: "Patna Sahib",
    financialUtilization: 142.0, // %
    physicalProgress: 54, // %
    fundReleasedDate: "2023-07-02",
    photoEvidenceStatus: "missing",
    daysSinceCompletion: 190,
    escalationSource: "ai",
    escalationNote: null,
    escalatedDate: null,
  },
  {
    workId: "MPLADS-BR-2024-0418",
    mpName: "Shri Ravi Shankar Prasad",
    state: "Bihar",
    district: "Patna",
    category: "Drinking Water Supply",
    description: "Installation of Solar-powered High Capacity RO Plant in Fatuha Ward 4",
    recommendedDate: "2023-06-15",
    sanctionDate: "2023-08-10",
    completionDate: "2024-06-30",
    sanctionedAmount: 42.00,
    expenditure: 40.50,
    status: "Under Review",
    riskScore: 64,
    riskLevel: "Medium",
    flagReason: "Ground water laboratory certificate upload pending from district nodal agency",
    vendorName: "Ganga Civil Solutions",
    riskFactorBreakdown: {
      costOverrun: 12,
      delaySlippage: 48,
      duplicateSimilarity: 25,
      vendorAnomaly: 15,
    },
    aiDiagnosticSummary: "Civil works complete (90%), but statutory water quality safety certification is overdue by 75 days before commissioning.",
    constituency: "Patna Sahib",
    financialUtilization: 96.4,
    physicalProgress: 90,
    fundReleasedDate: "2023-08-25",
    photoEvidenceStatus: "missing",
    daysSinceCompletion: 55,
    escalationSource: "ai",
    escalationNote: null,
    escalatedDate: null,
  },
  {
    workId: "MPLADS-BR-2024-0422",
    mpName: "Shri Ravi Shankar Prasad",
    state: "Bihar",
    district: "Patna",
    category: "Education & Smart Classrooms",
    description: "Setup of 10 Smart Interactive Classrooms in Patna High School, Gardanibagh",
    recommendedDate: "2023-03-10",
    sanctionDate: "2023-05-15",
    completionDate: "2023-11-20",
    sanctionedAmount: 65.00,
    expenditure: 64.20,
    status: "Completed",
    riskScore: 12,
    riskLevel: "Low",
    flagReason: "Completed within SLA parameters with geotagged digital logs",
    vendorName: "Southern Tech Labs",
    riskFactorBreakdown: {
      costOverrun: 2,
      delaySlippage: 5,
      duplicateSimilarity: 3,
      vendorAnomaly: 2,
    },
    aiDiagnosticSummary: "Hardware assets verified via QR registry; classroom telemetry active and confirmed by school principal.",
    constituency: "Patna Sahib",
    financialUtilization: 98.8,
    physicalProgress: 100,
    fundReleasedDate: "2023-05-28",
    photoEvidenceStatus: "verified",
    daysSinceCompletion: 278,
    escalationSource: null,
    escalationNote: null,
    escalatedDate: null,
  },
  {
    workId: "MPLADS-BR-2024-0710",
    mpName: "Shri Ram Kripal Yadav",
    state: "Bihar",
    district: "Patna",
    category: "Rural Roads & Bridges",
    description: "Construction of PCC Road with side drain from Bihta Chowk to Mahadev Temple",
    recommendedDate: "2023-05-18",
    sanctionDate: "2023-07-22",
    completionDate: "2024-03-10",
    sanctionedAmount: 72.00,
    expenditure: 71.50,
    status: "Completed",
    riskScore: 78,
    riskLevel: "High",
    flagReason: "Physical completion claimed by contractor but zero geotagged photos uploaded for 165 days",
    vendorName: "M/s Apex Infra Projects",
    riskFactorBreakdown: {
      costOverrun: 15,
      delaySlippage: 25,
      duplicateSimilarity: 20,
      vendorAnomaly: 40,
    },
    aiDiagnosticSummary: "100% funds disbursed, but ground verification queue indicates complete lack of mandatory completion photography or citizen signage.",
    constituency: "Pataliputra",
    financialUtilization: 99.3,
    physicalProgress: 100,
    fundReleasedDate: "2023-08-05",
    photoEvidenceStatus: "missing",
    daysSinceCompletion: 167,
    escalationSource: "district",
    escalationNote: "Contractor failed to provide completion photo evidence despite two DNO reminder notices.",
    escalatedDate: "2024-07-15",
  },
  {
    workId: "MPLADS-BR-2024-0716",
    mpName: "Shri Ram Kripal Yadav",
    state: "Bihar",
    district: "Patna",
    category: "Drinking Water Supply",
    description: "Community Drinking Water Tank & Solar Pumping Station in Maner Block",
    recommendedDate: "2023-08-05",
    sanctionDate: "2023-10-14",
    completionDate: "2024-04-25",
    sanctionedAmount: 54.00,
    expenditure: 53.20,
    status: "Completed",
    riskScore: 58,
    riskLevel: "Medium",
    flagReason: "Post-completion water test certificate and valve photo documentation missing",
    vendorName: "Ganga Civil Solutions",
    riskFactorBreakdown: {
      costOverrun: 10,
      delaySlippage: 30,
      duplicateSimilarity: 10,
      vendorAnomaly: 50,
    },
    aiDiagnosticSummary: "Completed on paper 120 days ago. Geotagged site image validation pending in district portal.",
    constituency: "Pataliputra",
    financialUtilization: 98.5,
    physicalProgress: 100,
    fundReleasedDate: "2023-11-01",
    photoEvidenceStatus: "missing",
    daysSinceCompletion: 121,
    escalationSource: "ai",
    escalationNote: null,
    escalatedDate: null,
  },
  {
    workId: "MPLADS-BR-2024-0801",
    mpName: "Shri Sushil Kumar Modi",
    state: "Bihar",
    district: "Patna",
    category: "Education & Smart Classrooms",
    description: "Modern Digital Science Lab & STEM Center at B.N. Collegiate School, Patna",
    recommendedDate: "2023-02-12",
    sanctionDate: "2023-04-18",
    completionDate: "2023-12-10",
    sanctionedAmount: 60.00,
    expenditure: 59.40,
    status: "Completed",
    riskScore: 20,
    riskLevel: "Low",
    flagReason: "Completed work with verified educational telemetry",
    vendorName: "Southern Tech Labs",
    riskFactorBreakdown: {
      costOverrun: 2,
      delaySlippage: 8,
      duplicateSimilarity: 5,
      vendorAnomaly: 5,
    },
    aiDiagnosticSummary: "Completed and operational. Lab telemetry active with 120+ verified experiment logs.",
    constituency: "Rajya Sabha (Bihar)",
    financialUtilization: 99.0,
    physicalProgress: 100,
    fundReleasedDate: "2023-05-02",
    photoEvidenceStatus: "verified",
    daysSinceCompletion: 258,
    escalationSource: null,
    escalationNote: null,
    escalatedDate: null,
  },
  {
    workId: "MPLADS-BR-2024-0808",
    mpName: "Shri Sushil Kumar Modi",
    state: "Bihar",
    district: "Patna",
    category: "Community Infrastructure",
    description: "Community Hall and Women Self-Help Group Training Center at Phulwari Sharif",
    recommendedDate: "2023-06-25",
    sanctionDate: "2023-08-30",
    completionDate: "2024-05-18",
    sanctionedAmount: 82.00,
    expenditure: 81.00,
    status: "Completed",
    riskScore: 35,
    riskLevel: "Low",
    flagReason: "Completion certificate filed, awaiting final photo upload from block engineer",
    vendorName: "Shreeji Infra LLP",
    riskFactorBreakdown: {
      costOverrun: 8,
      delaySlippage: 12,
      duplicateSimilarity: 8,
      vendorAnomaly: 7,
    },
    aiDiagnosticSummary: "Completed on 18 May 2024; pending district photo evidence approval before closure.",
    constituency: "Rajya Sabha (Bihar)",
    financialUtilization: 98.8,
    physicalProgress: 100,
    fundReleasedDate: "2023-09-15",
    photoEvidenceStatus: "missing",
    daysSinceCompletion: 98,
    escalationSource: null,
    escalationNote: null,
    escalatedDate: null,
  },
  {
    workId: "MPLADS-BR-2024-0912",
    mpName: "Dr. Akhilesh Prasad Singh",
    state: "Bihar",
    district: "Patna",
    category: "Healthcare Facilities",
    description: "Ambulance Fleet & Mobile Medical Testing Unit for Rural Panchayats in Masaurhi",
    recommendedDate: "2023-09-10",
    sanctionDate: "2023-11-20",
    completionDate: "2024-06-12",
    sanctionedAmount: 68.00,
    expenditure: 67.50,
    status: "Completed",
    riskScore: 72,
    riskLevel: "High",
    flagReason: "Mobile medical unit delivered but GPS tracking beacon inactive and vehicle photos missing",
    vendorName: "Central MedTech Systems",
    riskFactorBreakdown: {
      costOverrun: 12,
      delaySlippage: 28,
      duplicateSimilarity: 15,
      vendorAnomaly: 45,
    },
    aiDiagnosticSummary: "Invoice settled for 3 mobile testing vans, but live GPS telemetry offline for 70+ days and delivery geotag photos unsubmitted.",
    constituency: "Rajya Sabha (Bihar)",
    financialUtilization: 99.2,
    physicalProgress: 100,
    fundReleasedDate: "2023-12-05",
    photoEvidenceStatus: "missing",
    daysSinceCompletion: 73,
    escalationSource: "ai",
    escalationNote: null,
    escalatedDate: null,
  },
  {
    workId: "MPLADS-BR-2024-0430",
    mpName: "Shri Ravi Shankar Prasad",
    state: "Bihar",
    district: "Patna",
    category: "Healthcare Facilities",
    description: "Modern Diagnostic Radiology Equipment Wing at Community Health Center, Bakhtiyarpur",
    recommendedDate: "2023-07-05",
    sanctionDate: "2023-09-12",
    completionDate: "2024-09-30",
    sanctionedAmount: 95.00,
    expenditure: 78.50,
    status: "Ongoing",
    riskScore: 28,
    riskLevel: "Low",
    flagReason: "Standard milestone execution on track",
    vendorName: "Central MedTech Systems",
    riskFactorBreakdown: {
      costOverrun: 8,
      delaySlippage: 14,
      duplicateSimilarity: 4,
      vendorAnomaly: 2,
    },
    aiDiagnosticSummary: "Structure 85% ready; medical machinery shipment cleared customs in Kolkata.",
    constituency: "Patna Sahib",
    financialUtilization: 82.6,
    physicalProgress: 85,
    fundReleasedDate: "2023-09-25",
  },
  {
    workId: "MPLADS-BR-2024-0438",
    mpName: "Shri Ravi Shankar Prasad",
    state: "Bihar",
    district: "Patna",
    category: "Community Infrastructure",
    description: "Public Digital Library & Youth Skill Center near Patna Sahib Railway Station",
    recommendedDate: "2023-05-20",
    sanctionDate: "2023-07-28",
    completionDate: "2024-01-15",
    sanctionedAmount: 58.00,
    expenditure: 57.10,
    status: "Completed",
    riskScore: 16,
    riskLevel: "Low",
    flagReason: "Asset commissioned and inaugurated",
    vendorName: "Shreeji Infra LLP",
    riskFactorBreakdown: {
      costOverrun: 4,
      delaySlippage: 8,
      duplicateSimilarity: 2,
      vendorAnomaly: 2,
    },
    aiDiagnosticSummary: "Fully operational. Biometric visitor access logging 250+ students daily.",
    constituency: "Patna Sahib",
    financialUtilization: 98.4,
    physicalProgress: 100,
    fundReleasedDate: "2023-08-10",
  },
  {
    workId: "MPLADS-BR-2024-0445",
    mpName: "Shri Ravi Shankar Prasad",
    state: "Bihar",
    district: "Patna",
    category: "Sanitation & Waste Mgmt",
    description: "Solid Waste Processing & Bio-methanation Facility for Patna City Market",
    recommendedDate: "2023-09-01",
    sanctionDate: "2023-11-10",
    completionDate: "2024-11-30",
    sanctionedAmount: 52.00,
    expenditure: 28.00,
    status: "Ongoing",
    riskScore: 32,
    riskLevel: "Low",
    flagReason: "Civil work progressing as per DPR milestones",
    vendorName: "Deccan CleanTech Corp",
    riskFactorBreakdown: {
      costOverrun: 5,
      delaySlippage: 16,
      duplicateSimilarity: 6,
      vendorAnomaly: 5,
    },
    aiDiagnosticSummary: "Foundation work completed; bio-digester assembly in progress.",
    constituency: "Patna Sahib",
    financialUtilization: 53.8,
    physicalProgress: 60,
    fundReleasedDate: "2023-11-20",
  },
  {
    workId: "MPLADS-BR-2024-0451",
    mpName: "Shri Ravi Shankar Prasad",
    state: "Bihar",
    district: "Patna",
    category: "Solar & Renewable Energy",
    description: "Installation of 200 LED Solar High-Mast Lights across Gram Panchayats in Danapur",
    recommendedDate: "2024-01-10",
    sanctionDate: "2024-02-28",
    completionDate: "2024-08-15",
    sanctionedAmount: 38.00,
    expenditure: 36.50,
    status: "Completed",
    riskScore: 14,
    riskLevel: "Low",
    flagReason: "All 200 poles geotagged and IoT telemetry verified",
    vendorName: "Kerala Solar CleanTech",
    riskFactorBreakdown: {
      costOverrun: 2,
      delaySlippage: 5,
      duplicateSimilarity: 4,
      vendorAnomaly: 3,
    },
    aiDiagnosticSummary: "IoT telemetry transmitting nightly illumination verification logs.",
    constituency: "Patna Sahib",
    financialUtilization: 96.0,
    physicalProgress: 100,
    fundReleasedDate: "2024-03-10",
  },
  {
    workId: "MPLADS-BR-2024-0460",
    mpName: "Shri Ravi Shankar Prasad",
    state: "Bihar",
    district: "Patna",
    category: "Rural Roads & Bridges",
    description: "Paver Block Road and Storm Drainage along Khagaul Canal Road",
    recommendedDate: "2024-02-05",
    sanctionDate: "2024-04-18",
    completionDate: "2024-12-31",
    sanctionedAmount: 48.00,
    expenditure: 12.00,
    status: "Sanctioned",
    riskScore: 22,
    riskLevel: "Low",
    flagReason: "Tendering process completed by District Nodal Officer",
    vendorName: "Eastern Buildtech Ltd",
    riskFactorBreakdown: {
      costOverrun: 4,
      delaySlippage: 10,
      duplicateSimilarity: 5,
      vendorAnomaly: 3,
    },
    aiDiagnosticSummary: "Contract awarded following competitive e-tender; contractor mobilization in progress.",
    constituency: "Patna Sahib",
    financialUtilization: 25.0,
    physicalProgress: 20,
    fundReleasedDate: "2024-05-02",
  },
  {
    workId: "MPLADS-UP-2024-2081",
    mpName: "Shri Narendra Modi",
    state: "Uttar Pradesh",
    district: "Varanasi",
    category: "Rural Roads & Bridges",
    description: "Interlocking Pavement & Solar Street Lighting Corridor in Rohaniya Block",
    recommendedDate: "2023-04-15",
    sanctionDate: "2023-06-20",
    completionDate: "2024-03-31",
    sanctionedAmount: 85.50, // Identical round figure
    expenditure: 84.80,
    status: "Under Review",
    riskScore: 82,
    riskLevel: "High",
    flagReason: "Contract splitting flag: Identical ₹85.50L bill of quantities released on same day as Bihar work #0412",
    vendorName: "M/s Apex Infra Projects",
    riskFactorBreakdown: {
      costOverrun: 20,
      delaySlippage: 25,
      duplicateSimilarity: 25,
      vendorAnomaly: 30,
    },
    aiDiagnosticSummary: "Cross-state procurement audit match: Same contractor awarded identical ₹85.50L contract across state borders within 48 hours of BOQ generation.",
    constituency: "Varanasi",
    financialUtilization: 99.1,
    physicalProgress: 80,
    expectedProgress: 100,
    fundReleasedDate: "2023-07-02", // SAME DAY as Bihar work #0412!
    photoEvidenceStatus: "missing",
    daysSinceCompletion: 145,
    escalationSource: "ai",
    caseStatus: "New",
  },
  {
    workId: "MPLADS-JH-2024-3199",
    mpName: "Shri Sanjay Seth",
    state: "Jharkhand",
    district: "Ranchi",
    category: "Rural Roads & Bridges",
    description: "Culvert & Bituminous Approach Road for Kanke Rural Panchayat",
    recommendedDate: "2023-04-18",
    sanctionDate: "2023-06-20",
    completionDate: "2024-04-15",
    sanctionedAmount: 85.50, // 3rd Identical round figure
    expenditure: 85.10,
    status: "Under Review",
    riskScore: 86,
    riskLevel: "High",
    flagReason: "3rd identical ₹85.50L contract release on 02-Jul-2023 (possible multi-state contract splitting)",
    vendorName: "M/s Apex Infra Projects",
    riskFactorBreakdown: {
      costOverrun: 22,
      delaySlippage: 28,
      duplicateSimilarity: 25,
      vendorAnomaly: 25,
    },
    aiDiagnosticSummary: "Automated treasury cross-reference trigger: 3 simultaneous ₹85.50L disbursements routed to M/s Apex Infra Projects across Bihar, UP, and Jharkhand on 02-Jul-2023.",
    constituency: "Ranchi",
    financialUtilization: 99.5,
    physicalProgress: 75,
    expectedProgress: 100,
    fundReleasedDate: "2023-07-02", // SAME DAY as Bihar and UP!
    photoEvidenceStatus: "missing",
    daysSinceCompletion: 130,
    escalationSource: "ai",
    caseStatus: "New",
  },
  {
    workId: "MPLADS-BR-2024-1102",
    mpName: "Shri Jitan Ram Manjhi",
    state: "Bihar",
    district: "Gaya",
    category: "Rural Roads & Bridges",
    description: "Rural Road Drainage & Paved Culvert Link in Bodh Gaya Sector 4",
    recommendedDate: "2023-05-02",
    sanctionDate: "2023-06-28",
    completionDate: "2024-05-20",
    sanctionedAmount: 85.50, // 4th Identical round figure
    expenditure: 82.00,
    status: "Delayed",
    riskScore: 79,
    riskLevel: "High",
    flagReason: "Single-bidder cartel concentration flag: 4th repeat ₹85.50L contract award",
    vendorName: "M/s Apex Infra Projects",
    riskFactorBreakdown: {
      costOverrun: 15,
      delaySlippage: 45,
      duplicateSimilarity: 15,
      vendorAnomaly: 25,
    },
    aiDiagnosticSummary: "Procurement collusion signature: Single bidder qualification following restrictive tender specification criteria.",
    constituency: "Gaya",
    financialUtilization: 95.9,
    physicalProgress: 70,
    expectedProgress: 100,
    fundReleasedDate: "2023-07-15",
    photoEvidenceStatus: "missing",
    daysSinceCompletion: 95,
    escalationSource: "district",
    escalationNote: "Contractor failed to mobilize equipment despite 70% advance drawal.",
    escalatedDate: "2024-06-10",
    caseStatus: "Escalated",
  },
  {
    workId: "MPLADS-UP-2024-1189",
    mpName: "Shri Akhilesh Yadav",
    state: "Uttar Pradesh",
    district: "Kannauj",
    category: "Education & Smart Classrooms",
    recommendedDate: "2023-08-10",
    sanctionDate: "2023-10-05",
    completionDate: "2024-05-30",
    sanctionedAmount: 48.00,
    expenditure: 46.50,
    status: "Under Review",
    riskScore: 88,
    riskLevel: "High",
    flagReason: "91% GIS & scope duplicate match with state PWD scheme #UP-PWD-881",
    vendorName: "Eastern Buildtech Ltd",
    riskFactorBreakdown: {
      costOverrun: 8,
      delaySlippage: 12,
      duplicateSimilarity: 68,
      vendorAnomaly: 12,
    },
    aiDiagnosticSummary: "High-confidence satellite coordinate overlap (within 15 meters) and identical bill of quantities (BOQ) text match with State PWD Project #UP-PWD-881.",
    constituency: "Kannauj",
    financialUtilization: 96.8,
    physicalProgress: 90,
    fundReleasedDate: "2023-10-18",
  },
  {
    workId: "MPLADS-MH-2024-0872",
    mpName: "Smt. Supriya Sule",
    state: "Maharashtra",
    district: "Baramati",
    category: "Drinking Water Supply",
    recommendedDate: "2023-02-15",
    sanctionDate: "2023-03-28",
    completionDate: "2023-11-10",
    sanctionedAmount: 62.00,
    expenditure: 61.20,
    status: "Completed",
    riskScore: 18,
    riskLevel: "Low",
    flagReason: "Normal execution within SLA parameters",
    vendorName: "Shreeji Water Infra LLP",
    riskFactorBreakdown: {
      costOverrun: 5,
      delaySlippage: 7,
      duplicateSimilarity: 3,
      vendorAnomaly: 3,
    },
    aiDiagnosticSummary: "Regular verification passed. All geotagged inspection reports, water quality lab certifications, and payment milestones correlate within 99% confidence.",
    constituency: "Baramati",
    financialUtilization: 98.7,
    physicalProgress: 100,
    fundReleasedDate: "2023-04-10",
  },
  {
    workId: "MPLADS-KA-2024-0341",
    mpName: "Shri Tejasvi Surya",
    state: "Karnataka",
    district: "Bengaluru South",
    category: "Community Infrastructure",
    recommendedDate: "2023-05-19",
    sanctionDate: "2023-07-14",
    completionDate: "2024-08-30",
    sanctionedAmount: 110.00,
    expenditure: 102.50,
    status: "Ongoing",
    riskScore: 35,
    riskLevel: "Low",
    flagReason: "Minor 14-day vendor invoice submission lag",
    vendorName: "Deccan Urban Builders",
    riskFactorBreakdown: {
      costOverrun: 10,
      delaySlippage: 18,
      duplicateSimilarity: 4,
      vendorAnomaly: 3,
    },
    aiDiagnosticSummary: "Project is on track. Physical milestone inspection confirmed 82% structure completion; minor documentary delay resolved.",
    constituency: "Bangalore South",
    financialUtilization: 93.1,
    physicalProgress: 82,
    fundReleasedDate: "2023-08-01",
  },
  {
    workId: "MPLADS-RJ-2024-0994",
    mpName: "Col. Rajyavardhan Rathore",
    state: "Rajasthan",
    district: "Jaipur Rural",
    category: "Healthcare Facilities",
    recommendedDate: "2023-03-01",
    sanctionDate: "2023-05-12",
    completionDate: "2024-01-30 (Overdue)",
    sanctionedAmount: 145.00,
    expenditure: 168.20,
    status: "Delayed",
    riskScore: 84,
    riskLevel: "High",
    flagReason: "Vendor concentration anomaly: 7th high-value award to single entity",
    vendorName: "M/s Apex Infra Projects",
    riskFactorBreakdown: {
      costOverrun: 28,
      delaySlippage: 32,
      duplicateSimilarity: 10,
      vendorAnomaly: 30,
    },
    aiDiagnosticSummary: "Procurement collusion alert: M/s Apex Infra Projects secured 76% of all rural health tenders in Jaipur Rural across 4 months with single-bid tenders.",
    constituency: "Jaipur Rural",
    financialUtilization: 116.0,
    physicalProgress: 60,
    fundReleasedDate: "2023-05-25",
  },
  {
    workId: "MPLADS-WB-2024-0619",
    mpName: "Dr. Kakoli Ghosh Dastidar",
    state: "West Bengal",
    district: "North 24 Parganas",
    category: "Sanitation & Waste Mgmt",
    recommendedDate: "2023-09-04",
    sanctionDate: "2023-11-18",
    completionDate: "2024-09-15",
    sanctionedAmount: 75.00,
    expenditure: 68.00,
    status: "Ongoing",
    riskScore: 68,
    riskLevel: "Medium",
    flagReason: "Disproportionate front-loading: 90% funds drawn at 35% civil completion",
    vendorName: "Ganga Civil Solutions",
    riskFactorBreakdown: {
      costOverrun: 38,
      delaySlippage: 20,
      duplicateSimilarity: 5,
      vendorAnomaly: 5,
    },
    aiDiagnosticSummary: "Disbursement velocity warning: Contractor received ₹68L advance disbursements against an audited ground completion level of merely 35%.",
    constituency: "Barasat",
    financialUtilization: 90.6,
    physicalProgress: 35,
    fundReleasedDate: "2023-12-05",
  },
  {
    workId: "MPLADS-KL-2024-0128",
    mpName: "Dr. Shashi Tharoor",
    state: "Kerala",
    district: "Thiruvananthapuram",
    category: "Solar & Renewable Energy",
    recommendedDate: "2023-01-20",
    sanctionDate: "2023-03-10",
    completionDate: "2023-10-15",
    sanctionedAmount: 55.00,
    expenditure: 53.80,
    status: "Completed",
    riskScore: 14,
    riskLevel: "Low",
    flagReason: "Completed with verified digital asset telemetry",
    vendorName: "Kerala Solar CleanTech",
    riskFactorBreakdown: {
      costOverrun: 2,
      delaySlippage: 6,
      duplicateSimilarity: 4,
      vendorAnomaly: 2,
    },
    aiDiagnosticSummary: "Benchmark implementation. Inverter telemetry transmitting live KWh generation metrics to National MPLADS Portal.",
    constituency: "Thiruvananthapuram",
    financialUtilization: 97.8,
    physicalProgress: 100,
    fundReleasedDate: "2023-03-25",
  },
  {
    workId: "MPLADS-JH-2024-1502",
    mpName: "Shri Nishikant Dubey",
    state: "Jharkhand",
    district: "Godda",
    category: "Drinking Water Supply",
    recommendedDate: "2023-06-11",
    sanctionDate: "2023-08-29",
    completionDate: "2024-04-10 (Overdue)",
    sanctionedAmount: 95.00,
    expenditure: 114.50,
    status: "Delayed",
    riskScore: 79,
    riskLevel: "High",
    flagReason: "Deep tube-well GPS coordinates mapped in non-habitable swamp area",
    vendorName: "Vanguard Constructions Pvt Ltd",
    riskFactorBreakdown: {
      costOverrun: 30,
      delaySlippage: 25,
      duplicateSimilarity: 15,
      vendorAnomaly: 9,
    },
    aiDiagnosticSummary: "Geospatial anomaly: Provided borewell latitude/longitude points coincide with protected wetland reserve with zero nearby residential beneficiaries.",
    constituency: "Godda",
    financialUtilization: 120.5,
    physicalProgress: 65,
    fundReleasedDate: "2023-09-12",
  },
  {
    workId: "MPLADS-MP-2024-0771",
    mpName: "Shri Alok Sharma",
    state: "Madhya Pradesh",
    district: "Bhopal",
    category: "Healthcare Facilities",
    recommendedDate: "2023-07-22",
    sanctionDate: "2023-09-30",
    completionDate: "2024-10-30",
    sanctionedAmount: 130.00,
    expenditure: 95.00,
    status: "Ongoing",
    riskScore: 56,
    riskLevel: "Medium",
    flagReason: "Medical equipment procurement delay exceeding 90 days",
    vendorName: "Central MedTech Systems",
    riskFactorBreakdown: {
      costOverrun: 12,
      delaySlippage: 36,
      duplicateSimilarity: 4,
      vendorAnomaly: 4,
    },
    aiDiagnosticSummary: "Civil structure complete, but critical ICU ventilator and diagnostic gear pending delivery from overseas supplier.",
    constituency: "Bhopal",
    financialUtilization: 73.0,
    physicalProgress: 70,
    fundReleasedDate: "2023-10-15",
  },
  {
    workId: "MPLADS-TN-2024-0533",
    mpName: "Thiru Dayanidhi Maran",
    state: "Tamil Nadu",
    district: "Chennai Central",
    category: "Education & Smart Classrooms",
    recommendedDate: "2023-02-05",
    sanctionDate: "2023-04-18",
    completionDate: "2023-12-20",
    sanctionedAmount: 88.00,
    expenditure: 87.40,
    status: "Completed",
    riskScore: 21,
    riskLevel: "Low",
    flagReason: "Standard compliance verified",
    vendorName: "Southern Tech Labs",
    riskFactorBreakdown: {
      costOverrun: 4,
      delaySlippage: 10,
      duplicateSimilarity: 5,
      vendorAnomaly: 2,
    },
    aiDiagnosticSummary: "All 18 government school computer labs installed and verified via QR-coded hardware asset registry.",
    constituency: "Chennai Central",
    financialUtilization: 99.3,
    physicalProgress: 100,
    fundReleasedDate: "2023-05-02",
  },
  {
    workId: "MPLADS-AS-2024-1240",
    mpName: "Shri Gaurav Gogoi",
    state: "Assam",
    district: "Kaliabor",
    category: "Rural Roads & Bridges",
    recommendedDate: "2023-05-14",
    sanctionDate: "2023-07-25",
    completionDate: "2024-03-31 (Overdue)",
    sanctionedAmount: 112.00,
    expenditure: 138.60,
    status: "Halted",
    riskScore: 95,
    riskLevel: "High",
    flagReason: "Culvert washed away during unseasonal rains; substandard concrete batch flagged",
    vendorName: "Brahmaputra Engineering Works",
    riskFactorBreakdown: {
      costOverrun: 35,
      delaySlippage: 40,
      duplicateSimilarity: 5,
      vendorAnomaly: 15,
    },
    aiDiagnosticSummary: "Quality test audit failure: 28-day concrete cube compressive strength test was 45% below IS-456 standards. Work halted by District Collector.",
    constituency: "Kaliabor",
    financialUtilization: 123.7,
    physicalProgress: 40,
    fundReleasedDate: "2023-08-10",
  },
  {
    workId: "MPLADS-GJ-2024-0498",
    mpName: "Shri C.R. Patil",
    state: "Gujarat",
    district: "Navsari",
    category: "Drinking Water Supply",
    recommendedDate: "2023-04-05",
    sanctionDate: "2023-06-12",
    completionDate: "2024-01-20",
    sanctionedAmount: 64.00,
    expenditure: 62.80,
    status: "Completed",
    riskScore: 16,
    riskLevel: "Low",
    flagReason: "Completed within allocated budget and schedule",
    vendorName: "Gujarat HydroTech Ltd",
    riskFactorBreakdown: {
      costOverrun: 3,
      delaySlippage: 6,
      duplicateSimilarity: 4,
      vendorAnomaly: 3,
    },
    aiDiagnosticSummary: "Verified pipeline distribution system. IoT flow-meter telematics confirm 45,000 LPD supply to 12 rural wards.",
    constituency: "Navsari",
    financialUtilization: 98.1,
    physicalProgress: 100,
    fundReleasedDate: "2023-06-25",
  },
  {
    workId: "MPLADS-OD-2024-0821",
    mpName: "Shri Pinaki Misra",
    state: "Odisha",
    district: "Puri",
    category: "Community Infrastructure",
    recommendedDate: "2023-08-12",
    sanctionDate: "2023-10-22",
    completionDate: "2024-11-30",
    sanctionedAmount: 92.00,
    expenditure: 80.00,
    status: "Ongoing",
    riskScore: 62,
    riskLevel: "Medium",
    flagReason: "Coastal CRZ environmental clearance documentation pending",
    vendorName: "Kalinga Coastal Infrastructure",
    riskFactorBreakdown: {
      costOverrun: 15,
      delaySlippage: 35,
      duplicateSimilarity: 5,
      vendorAnomaly: 7,
    },
    aiDiagnosticSummary: "Cyclone shelter construction underway; pending MoEFCC clearance for revised structural footprint extension.",
    constituency: "Puri",
    financialUtilization: 86.9,
    physicalProgress: 68,
    fundReleasedDate: "2023-11-10",
  },
  {
    workId: "MPLADS-PB-2024-0667",
    mpName: "Shri Gurjeet Singh Aujla",
    state: "Punjab",
    district: "Amritsar",
    category: "Healthcare Facilities",
    recommendedDate: "2023-03-25",
    sanctionDate: "2023-05-18",
    completionDate: "2024-02-28",
    sanctionedAmount: 78.00,
    expenditure: 98.40,
    status: "Under Review",
    riskScore: 76,
    riskLevel: "High",
    flagReason: "26% unbudgeted cost inflation on sub-contracted civil masonry",
    vendorName: "Apex Infra Projects",
    riskFactorBreakdown: {
      costOverrun: 44,
      delaySlippage: 20,
      duplicateSimilarity: 4,
      vendorAnomaly: 8,
    },
    aiDiagnosticSummary: "Multiple variation orders submitted without technical sanction by executive engineer; expenditure exceeded 125% of baseline sanction.",
    constituency: "Amritsar",
    financialUtilization: 126.1,
    physicalProgress: 88,
    fundReleasedDate: "2023-06-05",
  },
  {
    workId: "MPLADS-TS-2024-0315",
    mpName: "Shri Asaduddin Owaisi",
    state: "Telangana",
    district: "Hyderabad",
    category: "Sanitation & Waste Mgmt",
    recommendedDate: "2023-06-18",
    sanctionDate: "2023-08-15",
    completionDate: "2024-04-30",
    sanctionedAmount: 105.00,
    expenditure: 101.20,
    status: "Completed",
    riskScore: 24,
    riskLevel: "Low",
    flagReason: "Fully commissioned smart waste segregation unit",
    vendorName: "Deccan CleanTech Corp",
    riskFactorBreakdown: {
      costOverrun: 4,
      delaySlippage: 12,
      duplicateSimilarity: 5,
      vendorAnomaly: 3,
    },
    aiDiagnosticSummary: "Completed and operational. Municipal waste handling efficiency increased by 38% in Old City sector.",
    constituency: "Hyderabad",
    financialUtilization: 96.3,
    physicalProgress: 100,
    fundReleasedDate: "2023-09-01",
  }
];

// Predictive Watchlist Data for Page 4 (Innovative AI Early Warning System)
// Projects currently categorized as healthy / ongoing, but with high AI escalation probability
export const mockPredictiveWatchlist = [
  {
    workId: "MPLADS-BR-2024-2201",
    mpName: "Shri Rajiv Pratap Rudy",
    state: "Bihar",
    district: "Saran",
    category: "Rural Roads & Bridges",
    currentStatus: "Ongoing",
    sanctionedAmount: 135.00,
    currentRiskScore: 32,
    predictedRiskScore30Days: 86,
    riskDeltaPercent: "+54%",
    warningSignal: "Fund utilization 28% behind milestone curve; zero geotagged labor attendance in 45 days",
    riskTrajectory: [14, 16, 19, 22, 28, 38, 56, 86],
    daysUntilPredictedThreshold: 11,
    vendorName: "Ganga Civil Solutions",
    riskFactorBreakdown: {
      costOverrun: 35,
      delaySlippage: 42,
      duplicateSimilarity: 10,
      vendorAnomaly: 13,
    },
    aiDiagnosticSummary: "AI early-warning model indicates sudden labor dropoff and subcontractor dispute. High probability of complete work stoppage within 14 days.",
    constituency: "Saran",
    physicalProgress: 38,
    financialUtilization: 22.4,
  },
  {
    workId: "MPLADS-UP-2024-3419",
    mpName: "Smt. Hema Malini",
    state: "Uttar Pradesh",
    district: "Mathura",
    category: "Drinking Water Supply",
    currentStatus: "Sanctioned",
    sanctionedAmount: 90.00,
    currentRiskScore: 24,
    predictedRiskScore30Days: 78,
    riskDeltaPercent: "+54%",
    warningSignal: "Vendor awarded 6 concurrent high-value works across 2 districts without equipment scaling",
    riskTrajectory: [12, 14, 15, 18, 24, 41, 60, 78],
    daysUntilPredictedThreshold: 14,
    vendorName: "M/s Apex Infra Projects",
    riskFactorBreakdown: {
      costOverrun: 20,
      delaySlippage: 30,
      duplicateSimilarity: 12,
      vendorAnomaly: 38,
    },
    aiDiagnosticSummary: "Capacity bottleneck detected: Contractor's active heavy machinery commitments exceed capacity by 340%. Immediate delivery defaults anticipated.",
    constituency: "Mathura",
    physicalProgress: 15,
    financialUtilization: 30.0,
  },
  {
    workId: "MPLADS-MH-2024-4108",
    mpName: "Shri Nitin Gadkari",
    state: "Maharashtra",
    district: "Nagpur",
    category: "Education & Smart Classrooms",
    currentStatus: "Ongoing",
    sanctionedAmount: 115.00,
    currentRiskScore: 29,
    predictedRiskScore30Days: 74,
    riskDeltaPercent: "+45%",
    warningSignal: "Material invoice unit rates 48% higher than current state Schedule of Rates (SoR)",
    riskTrajectory: [15, 16, 20, 22, 29, 44, 58, 74],
    daysUntilPredictedThreshold: 18,
    vendorName: "Vanguard Constructions Pvt Ltd",
    riskFactorBreakdown: {
      costOverrun: 52,
      delaySlippage: 22,
      duplicateSimilarity: 14,
      vendorAnomaly: 12,
    },
    aiDiagnosticSummary: "Procurement price surge alert: Hardware unit costs for interactive panels submitted at ₹1.45L vs approved ceiling of ₹98K.",
    constituency: "Nagpur",
    physicalProgress: 52,
    financialUtilization: 68.0,
  },
  {
    workId: "MPLADS-RJ-2024-1876",
    mpName: "Shri Rahul Kaswan",
    state: "Rajasthan",
    district: "Churu",
    category: "Healthcare Facilities",
    currentStatus: "Ongoing",
    sanctionedAmount: 160.00,
    currentRiskScore: 31,
    predictedRiskScore30Days: 73,
    riskDeltaPercent: "+42%",
    warningSignal: "Sub-surface water table mismatch risking structural foundation redesign",
    riskTrajectory: [16, 18, 21, 25, 31, 46, 59, 73],
    daysUntilPredictedThreshold: 20,
    vendorName: "Thar Infrastructure Ltd",
    riskFactorBreakdown: {
      costOverrun: 40,
      delaySlippage: 45,
      duplicateSimilarity: 5,
      vendorAnomaly: 10,
    },
    aiDiagnosticSummary: "Geotechnical survey report divergence: High soil salinity requires unbudgeted pile foundation modification costing approx ₹42L extra.",
    constituency: "Churu",
    physicalProgress: 30,
    financialUtilization: 41.2,
  },
  {
    workId: "MPLADS-WB-2024-5512",
    mpName: "Shri Abhishek Banerjee",
    state: "West Bengal",
    district: "Diamond Harbour",
    category: "Sanitation & Waste Mgmt",
    currentStatus: "Ongoing",
    sanctionedAmount: 80.00,
    currentRiskScore: 34,
    predictedRiskScore30Days: 72,
    riskDeltaPercent: "+38%",
    warningSignal: "Zero contractor response to 3 consecutive District Nodal Officer audit notices",
    riskTrajectory: [18, 20, 24, 28, 34, 49, 61, 72],
    daysUntilPredictedThreshold: 22,
    vendorName: "Eastern Buildtech Ltd",
    riskFactorBreakdown: {
      costOverrun: 25,
      delaySlippage: 48,
      duplicateSimilarity: 12,
      vendorAnomaly: 15,
    },
    aiDiagnosticSummary: "Administrative non-compliance trigger. Vendor failed to upload Q2 audited expenditure certificates to PFMS portal.",
    constituency: "Diamond Harbour",
    physicalProgress: 45,
    financialUtilization: 60.0,
  },
  {
    workId: "MPLADS-KA-2024-2980",
    mpName: "Shri P.C. Mohan",
    state: "Karnataka",
    district: "Bengaluru Central",
    category: "Community Infrastructure",
    currentStatus: "Ongoing",
    sanctionedAmount: 140.00,
    currentRiskScore: 36,
    predictedRiskScore30Days: 69,
    riskDeltaPercent: "+33%",
    warningSignal: "Public utility line relocation pending municipal clearance for 75 days",
    riskTrajectory: [20, 22, 25, 30, 36, 48, 58, 69],
    daysUntilPredictedThreshold: 26,
    vendorName: "Deccan Urban Builders",
    riskFactorBreakdown: {
      costOverrun: 20,
      delaySlippage: 65,
      duplicateSimilarity: 5,
      vendorAnomaly: 10,
    },
    aiDiagnosticSummary: "Inter-agency dependency blocker: BESCOM electric cabling relocation stalling foundation casting on 4 community community centers.",
    constituency: "Bangalore Central",
    physicalProgress: 40,
    financialUtilization: 45.0,
  },
  {
    workId: "MPLADS-JH-2024-6310",
    mpName: "Shri Jayant Sinha",
    state: "Jharkhand",
    district: "Hazaribagh",
    category: "Drinking Water Supply",
    currentStatus: "Sanctioned",
    sanctionedAmount: 75.00,
    currentRiskScore: 28,
    predictedRiskScore30Days: 59,
    riskDeltaPercent: "+31%",
    warningSignal: "No tender issuance 60 days post fund release; funds lying idle in treasury",
    riskTrajectory: [15, 17, 20, 22, 28, 38, 47, 59],
    daysUntilPredictedThreshold: 34,
    vendorName: "Not yet appointed (Tender delayed)",
    riskFactorBreakdown: {
      costOverrun: 10,
      delaySlippage: 75,
      duplicateSimilarity: 5,
      vendorAnomaly: 10,
    },
    aiDiagnosticSummary: "Fund park risk: First installment of ₹37.5L released to district treasury remains idle beyond statutory 45-day tender initiation window.",
    constituency: "Hazaribagh",
    physicalProgress: 0,
    financialUtilization: 0,
  }
];

// National State-Wise Aggregate Statistics (for National Overview Centerpiece)
export const mockStateRiskData = [
  { state: "Uttar Pradesh", code: "UP", totalWorks: 3840, sanctionedCr: 1820.5, completed: 2790, flaggedCount: 312, highRisk: 142, medRisk: 110, lowRisk: 60, riskIndex: 8.1 },
  { state: "Bihar", code: "BR", totalWorks: 2950, sanctionedCr: 1410.2, completed: 1980, flaggedCount: 285, highRisk: 138, medRisk: 95, lowRisk: 52, riskIndex: 9.6 },
  { state: "Maharashtra", code: "MH", totalWorks: 3410, sanctionedCr: 1650.0, completed: 2850, flaggedCount: 198, highRisk: 72, medRisk: 86, lowRisk: 40, riskIndex: 5.8 },
  { state: "West Bengal", code: "WB", totalWorks: 2600, sanctionedCr: 1280.0, completed: 1840, flaggedCount: 224, highRisk: 98, medRisk: 82, lowRisk: 44, riskIndex: 8.6 },
  { state: "Rajasthan", code: "RJ", totalWorks: 2180, sanctionedCr: 1050.8, completed: 1620, flaggedCount: 178, highRisk: 84, medRisk: 64, lowRisk: 30, riskIndex: 8.1 },
  { state: "Madhya Pradesh", code: "MP", totalWorks: 2420, sanctionedCr: 1190.4, completed: 1810, flaggedCount: 154, highRisk: 62, medRisk: 58, lowRisk: 34, riskIndex: 6.3 },
  { state: "Karnataka", code: "KA", totalWorks: 2100, sanctionedCr: 1040.0, completed: 1790, flaggedCount: 112, highRisk: 40, medRisk: 48, lowRisk: 24, riskIndex: 5.3 },
  { state: "Tamil Nadu", code: "TN", totalWorks: 2540, sanctionedCr: 1220.0, completed: 2280, flaggedCount: 94, highRisk: 28, medRisk: 42, lowRisk: 24, riskIndex: 3.7 },
  { state: "Gujarat", code: "GJ", totalWorks: 2250, sanctionedCr: 1110.0, completed: 2010, flaggedCount: 88, highRisk: 26, medRisk: 38, lowRisk: 24, riskIndex: 3.9 },
  { state: "Jharkhand", code: "JH", totalWorks: 1320, sanctionedCr: 640.5, completed: 890, flaggedCount: 146, highRisk: 74, medRisk: 48, lowRisk: 24, riskIndex: 11.0 },
  { state: "Assam", code: "AS", totalWorks: 1250, sanctionedCr: 590.2, completed: 810, flaggedCount: 128, highRisk: 64, medRisk: 42, lowRisk: 22, riskIndex: 10.2 },
  { state: "Odisha", code: "OD", totalWorks: 1780, sanctionedCr: 860.0, completed: 1340, flaggedCount: 115, highRisk: 48, medRisk: 45, lowRisk: 22, riskIndex: 6.4 },
  { state: "Kerala", code: "KL", totalWorks: 1650, sanctionedCr: 790.0, completed: 1510, flaggedCount: 42, highRisk: 10, medRisk: 18, lowRisk: 14, riskIndex: 2.5 },
  { state: "Punjab", code: "PB", totalWorks: 1190, sanctionedCr: 580.0, completed: 940, flaggedCount: 82, highRisk: 36, medRisk: 30, lowRisk: 16, riskIndex: 6.8 },
  { state: "Telangana", code: "TS", totalWorks: 1480, sanctionedCr: 720.0, completed: 1270, flaggedCount: 68, highRisk: 22, medRisk: 30, lowRisk: 16, riskIndex: 4.5 },
  { state: "Andhra Pradesh", code: "AP", totalWorks: 1850, sanctionedCr: 910.0, completed: 1510, flaggedCount: 96, highRisk: 34, medRisk: 40, lowRisk: 22, riskIndex: 5.1 },
];

// Monthly Anomaly Time-Series Trends Data
export const mockMonthlyTrends = [
  { month: "Sep 2023", totalFlagged: 98, costOverrun: 42, delayStall: 36, duplicateGIS: 12, vendorCollusion: 8 },
  { month: "Oct 2023", totalFlagged: 114, costOverrun: 48, delayStall: 42, duplicateGIS: 14, vendorCollusion: 10 },
  { month: "Nov 2023", totalFlagged: 135, costOverrun: 58, delayStall: 49, duplicateGIS: 16, vendorCollusion: 12 },
  { month: "Dec 2023", totalFlagged: 162, costOverrun: 72, delayStall: 58, duplicateGIS: 18, vendorCollusion: 14 },
  { month: "Jan 2024", totalFlagged: 188, costOverrun: 84, delayStall: 65, duplicateGIS: 22, vendorCollusion: 17 },
  { month: "Feb 2024", totalFlagged: 215, costOverrun: 96, delayStall: 74, duplicateGIS: 25, vendorCollusion: 20 },
  { month: "Mar 2024", totalFlagged: 268, costOverrun: 120, delayStall: 91, duplicateGIS: 32, vendorCollusion: 25 },
  { month: "Apr 2024", totalFlagged: 242, costOverrun: 108, delayStall: 83, duplicateGIS: 28, vendorCollusion: 23 },
  { month: "May 2024", totalFlagged: 230, costOverrun: 102, delayStall: 78, duplicateGIS: 26, vendorCollusion: 24 },
  { month: "Jun 2024", totalFlagged: 210, costOverrun: 92, delayStall: 72, duplicateGIS: 24, vendorCollusion: 22 },
  { month: "Jul 2024", totalFlagged: 195, costOverrun: 86, delayStall: 67, duplicateGIS: 22, vendorCollusion: 20 },
  { month: "Aug 2024", totalFlagged: 182, costOverrun: 78, delayStall: 64, duplicateGIS: 21, vendorCollusion: 19 },
];

// Anomaly Distribution by Category
export const mockCategoryAnomalies = [
  { category: "Rural Roads & Bridges", count: 684, costShare: 42, delayShare: 35, duplicateShare: 23 },
  { category: "Drinking Water Supply", count: 492, costShare: 28, delayShare: 48, duplicateShare: 24 },
  { category: "Education & Classrooms", count: 378, costShare: 32, delayShare: 28, duplicateShare: 40 },
  { category: "Healthcare Facilities", count: 324, costShare: 46, delayShare: 38, duplicateShare: 16 },
  { category: "Sanitation & Waste Mgmt", count: 286, costShare: 30, delayShare: 44, duplicateShare: 26 },
  { category: "Community Infrastructure", count: 180, costShare: 24, delayShare: 56, duplicateShare: 20 },
];

// Vendor Concentration & Risk Matrix
export const mockTopVendors = [
  { vendor: "M/s Apex Infra Projects", worksAwarded: 48, totalAmountCr: 68.4, flaggedCount: 19, riskRatio: "39.5%", stateConcentration: "Bihar, UP, Rajasthan", isSuspicious: true },
  { vendor: "Ganga Civil Solutions", worksAwarded: 36, totalAmountCr: 44.2, flaggedCount: 14, riskRatio: "38.8%", stateConcentration: "West Bengal, Bihar", isSuspicious: true },
  { vendor: "Eastern Buildtech Ltd", worksAwarded: 32, totalAmountCr: 38.5, flaggedCount: 11, riskRatio: "34.3%", stateConcentration: "UP, West Bengal", isSuspicious: true },
  { vendor: "Vanguard Constructions", worksAwarded: 29, totalAmountCr: 36.0, flaggedCount: 9, riskRatio: "31.0%", stateConcentration: "Jharkhand, Maharashtra", isSuspicious: true },
  { vendor: "Brahmaputra Engg Works", worksAwarded: 22, totalAmountCr: 28.2, flaggedCount: 8, riskRatio: "36.3%", stateConcentration: "Assam, Northeast", isSuspicious: true },
  { vendor: "Deccan Urban Builders", worksAwarded: 42, totalAmountCr: 52.8, flaggedCount: 4, riskRatio: "9.5%", stateConcentration: "Karnataka, Telangana", isSuspicious: false },
  { vendor: "Gujarat HydroTech Ltd", worksAwarded: 38, totalAmountCr: 46.1, flaggedCount: 3, riskRatio: "7.8%", stateConcentration: "Gujarat, Maharashtra", isSuspicious: false },
  { vendor: "Southern Tech Labs", worksAwarded: 34, totalAmountCr: 32.5, flaggedCount: 2, riskRatio: "5.8%", stateConcentration: "Tamil Nadu, Kerala", isSuspicious: false },
];
